spring.datasource.url = jdbc:mysql://localhost:3306/todos
spring.datasource.username = root
spring.datasource.password = root

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update

app.jwt-secret = a5f3ad0d95c2afe089bc751a56f8a0f34e19bb28c528263d9135ac0ea45ba708
app.jwt-expiration-milliseconds = 604800000

